apiVersion: v1
kind: Service
metadata:
  name: node-api-service
spec:
  selector:
    app: node-api
  ports:
    - protocol: TCP
      port: 80 # The port the service will listen on
      targetPort: 3000 # The port your application is running on inside the container
  type: NodePort # Exposes the service on a port on each node's IP
